# Generated by Django 5.1b1 on 2024-08-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_count_of_likes_likesofthepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesofthepost',
            name='post',
            field=models.IntegerField(),
        ),
    ]
